server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: bulb_db
  sslmode: disable
  
jwt:
  secret: your-secret-key-here
  expiresin: 24